services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: postgres
      POSTGRES_DB: scanner
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
